name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Buildozer
      uses: artem-sheremet/buildozer-action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
