name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-venv \
          openjdk-11-jdk \
          git \
          zip \
          unzip
        
        pip3 install buildozer
    
    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug
