name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Buildozer
      uses: ugglesk/buildozer-action@v1
      with:
        work-dir: .
        buildozer-version: stable
    - uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        retention-days: 1
